import {
  copyFileSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join } from "node:path";
import YAML from "yaml";
import { loadConfig, type FixLoopConfig } from "../config/config.js";

export const CONFIG_FILE = "fixloop.config.yaml";
export const ENV_FILE = ".env";

/** Non-secret wizard answers, safe to persist in YAML. */
export interface WizardConfig {
  provider: string;
  /** Maps the provider's project name (e.g. BugSink project_name) to a repo. */
  providerProject: string;
  publicUrl: string;
  repository: string;
  defaultBranch: string;
  commands: {
    install: string;
    test: string;
    lint?: string;
    typecheck?: string;
  };
  githubAuthMethod: "token" | "app";
  aiProvider: string;
  model: string;
  /** Runner image that passed validation during setup. */
  runnerImage: string;
}

/** Secret wizard answers; only ever written to .env, never to YAML. */
export interface WizardSecrets {
  webhookSecret: string;
  githubToken?: string;
  aiApiKey?: string;
}

export interface ExistingInstall {
  hasConfig: boolean;
  hasEnv: boolean;
  /** Parsed YAML config when present and valid. */
  config?: FixLoopConfig;
  /** Present-but-unparseable YAML (surfaced so the wizard can warn). */
  configError?: string;
  /** Names of keys in .env — values are never read into this structure. */
  envKeys: string[];
}

/** Env var holding the API key for each AI provider OpenCode can use. */
export const AI_PROVIDER_ENV: Record<string, string> = {
  anthropic: "ANTHROPIC_API_KEY",
  openai: "OPENAI_API_KEY",
  zai: "ZAI_API_KEY",
  openrouter: "OPENROUTER_API_KEY",
  "openai-compatible": "OPENAI_COMPATIBLE_API_KEY",
};

/** Build the non-secret YAML config. Must never contain secrets. */
export function buildYaml(cfg: WizardConfig): string {
  const doc = {
    provider: cfg.provider,
    publicUrl: cfg.publicUrl,
    githubAuthMethod: cfg.githubAuthMethod,
    aiProvider: cfg.aiProvider,
    model: cfg.model,
    runnerImage: cfg.runnerImage,
    repositories: {
      [cfg.providerProject]: {
        providerProject: cfg.providerProject,
        github: {
          repository: cfg.repository,
          defaultBranch: cfg.defaultBranch,
        },
        commands: {
          install: cfg.commands.install,
          test: cfg.commands.test,
          ...(cfg.commands.lint ? { lint: cfg.commands.lint } : {}),
          ...(cfg.commands.typecheck
            ? { typecheck: cfg.commands.typecheck }
            : {}),
        },
      },
    },
  };
  return (
    "# Generated by `fixloop setup`. Edit with care; secrets live in .env.\n" +
    YAML.stringify(doc)
  );
}

/**
 * Build .env content: managed keys are set from the wizard secrets,
 * unrelated existing keys are preserved.
 */
export function buildEnv(
  secrets: WizardSecrets,
  existing: Record<string, string>,
  aiProvider: string,
): string {
  const merged: Record<string, string> = { ...existing };
  merged["FIXLOOP_WEBHOOK_SECRET"] = secrets.webhookSecret;
  if (secrets.githubToken) merged["GITHUB_TOKEN"] = secrets.githubToken;
  const aiEnvVar = AI_PROVIDER_ENV[aiProvider];
  if (aiEnvVar && secrets.aiApiKey) merged[aiEnvVar] = secrets.aiApiKey;

  const lines = [
    "# Generated by `fixloop setup`. Never commit this file.",
    ...Object.entries(merged).map(([k, v]) => `${k}=${v}`),
  ];
  return lines.join("\n") + "\n";
}

/** Parse .env into a key→value map (values stay local to this module). */
export function parseEnv(content: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    out[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
  }
  return out;
}

/**
 * Write a file atomically: temp file in the same directory, then rename.
 * A crash leaves either the old or the new content, never a partial file.
 */
export function writeFileAtomic(
  targetPath: string,
  content: string,
  mode?: number,
): void {
  const dir = dirname(targetPath);
  const tmpDir = mkdtempSync(join(dir, ".tmp-"));
  const tmpPath = join(tmpDir, basename(targetPath));
  try {
    writeFileSync(tmpPath, content, { mode });
    renameSync(tmpPath, targetPath);
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}

/** Copy an existing file to a timestamped backup. Returns the backup path. */
export function backupFile(targetPath: string): string | undefined {
  if (!existsSync(targetPath)) return undefined;
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = `${targetPath}.bak.${stamp}`;
  copyFileSync(targetPath, backupPath);
  return backupPath;
}

export function detectExisting(dir: string): ExistingInstall {
  const configPath = join(dir, CONFIG_FILE);
  const envPath = join(dir, ENV_FILE);
  const found: ExistingInstall = {
    hasConfig: existsSync(configPath),
    hasEnv: existsSync(envPath),
    envKeys: [],
  };
  if (found.hasConfig) {
    try {
      found.config = loadConfig(configPath);
    } catch (err) {
      found.configError = (err as Error).message;
    }
  }
  if (found.hasEnv) {
    found.envKeys = Object.keys(parseEnv(readFileSync(envPath, "utf8")));
  }
  return found;
}

/**
 * Persist the wizard result. Existing files are backed up first, then
 * replaced atomically. .env is written owner-read-only (0600).
 */
export function saveInstall(
  dir: string,
  cfg: WizardConfig,
  secrets: WizardSecrets,
): { backups: string[] } {
  const backups: string[] = [];
  const configPath = join(dir, CONFIG_FILE);
  const envPath = join(dir, ENV_FILE);

  const existingEnv = existsSync(envPath)
    ? parseEnv(readFileSync(envPath, "utf8"))
    : {};

  for (const p of [configPath, envPath]) {
    const b = backupFile(p);
    if (b) backups.push(b);
  }

  writeFileAtomic(configPath, buildYaml(cfg));
  writeFileAtomic(envPath, buildEnv(secrets, existingEnv, cfg.aiProvider), 0o600);
  return { backups };
}
