import type { DockerRunner } from "./docker/runner.js";
import type { CodingAgent } from "./agent/opencode.js";
import type { ErrorContext } from "./providers/error-provider.js";
import type { GitHubClient } from "./github/client.js";
import { RepairWorkflow } from "./workflow/repair.js";
import { VerificationGate } from "./verify/gate.js";

export interface FixLoopOptions {
  repoUrl: string;
  testCommand: string[];
  owner: string;
  repo: string;
  image?: string;
}

export interface FixLoopOutcome {
  prCreated: boolean;
  prUrl?: string;
  reason?: string;
}

/**
 * Sanitizes an error message for inclusion in a public PR body.
 * Redacts patterns that look like secrets (API keys, tokens, passwords).
 */
export function sanitizeForPr(text: string): string {
  return (
    text
      // API keys, tokens, secrets (common prefixes).
      .replace(
        /\b(sk-[a-zA-Z0-9_-]{10,}|ghp_[a-zA-Z0-9]{10,}|gho_[a-zA-Z0-9]{10,}|xox[bap]-[a-zA-Z0-9-]{10,}|AKIA[0-9A-Z]{16})\b/g,
        "[REDACTED]",
      )
      // Generic key=value with secret-like keys.
      .replace(
        /\b(api[_-]?key|token|secret|password|passwd|pwd)\s*[:=]\s*['"]?[^'"\s,;]+['"]?/gi,
        "$1=[REDACTED]",
      )
      // Bearer tokens.
      .replace(/\bBearer\s+[a-zA-Z0-9._-]{10,}\b/g, "Bearer [REDACTED]")
      // Credentials embedded in URLs (postgres://user:pass@host/db).
      .replace(
        /([a-z][a-z0-9+.-]*:\/\/[^/\s:@]+:)[^@\s/]+@/gi,
        "$1[REDACTED]@",
      )
  );
}

/**
 * FixLoop orchestrator: Error → RED → Fix → GREEN → Verify → PR.
 *
 * A PR is created ONLY if:
 * 1. RED is proven (tests fail before the fix).
 * 2. GREEN is proven (tests pass after the fix).
 * 3. Independent verification passes (fresh container, same diff).
 *
 * If any gate fails, NO PR is created. Never auto-merges.
 */
export class FixLoop {
  constructor(
    private runner: DockerRunner,
    private agent: CodingAgent,
    private github: GitHubClient,
    private opts: FixLoopOptions,
  ) {}

  async handleError(error: ErrorContext): Promise<FixLoopOutcome> {
    // Phase 7: RED → Fix → GREEN.
    const workflow = new RepairWorkflow(this.runner, this.agent, {
      repoUrl: this.opts.repoUrl,
      testCommand: this.opts.testCommand,
      image: this.opts.image,
    });
    const repair = await workflow.repair(error);

    if (!repair.redProven) {
      return {
        prCreated: false,
        reason: "Could not reproduce the bug (RED not proven).",
      };
    }
    if (!repair.fixApplied || !repair.greenProven || !repair.diff) {
      return {
        prCreated: false,
        reason: "Fix did not make tests pass (GREEN not proven).",
      };
    }
    if (!repair.changedFiles || repair.changedFiles.length === 0) {
      return {
        prCreated: false,
        reason: "Fix produced no changed files.",
      };
    }

    // Phase 8: Independent verification in a fresh container.
    const gate = new VerificationGate(this.runner, {
      repoUrl: this.opts.repoUrl,
      testCommand: this.opts.testCommand,
      image: this.opts.image,
    });
    const verdict = await gate.verify(repair.diff);
    if (!verdict.passed) {
      return {
        prCreated: false,
        reason: `Independent verification failed: ${verdict.reason}`,
      };
    }

    // Phase 9: Create the PR with the actual fix. Never auto-merge.
    // Sanitize the error message to avoid leaking secrets in the public PR.
    const branch = `fix/${error.issueId}-${Date.now()}`;
    const pr = await this.github.createFixPr({
      branch,
      base: "main",
      title: `fix: ${error.exception.type} in ${error.issueId}`,
      body: [
        `Fixes ${error.provider} issue ${error.issueId}.`,
        ``,
        `**Error:** ${error.exception.type}: ${sanitizeForPr(error.exception.message)}`,
        ``,
        `**Verification:**`,
        `- RED proven: tests failed before the fix.`,
        `- GREEN proven: tests passed after the fix.`,
        `- Independent verification: passed in a fresh container.`,
        ``,
        `This PR was generated by FixLoop. Human review required — never auto-merged.`,
      ].join("\n"),
      changedFiles: repair.changedFiles,
    });

    return { prCreated: true, prUrl: pr.url };
  }
}
